name: Deploy DockerNginx

on:
push:
branches:
      - main

jobs:
build-and-push:
runs-on: ubuntu-latest

steps:
      - name: Checkout Repository
uses: actions/checkout@v4

      - name: Log in to Docker Hub
uses: docker/login-action@v3
with:
username: ${{ secrets.Mukthaml2002 }}
password: ${{ secrets.muktha122002 }}

      - name: Build Docker Image
run: |
docker build -t Mukthaml2002/nginx-html:latest .

      - name: Push Docker Image to Docker Hub
run: |
docker push Mukthaml2002/nginx-html:latest

